# https://docs.travis-ci.com/user/languages/python/

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - coverage run --source ./Notes -m pytest

after_success:
  - coveralls

branches:
  only:
  - master
  - develop
