# https://docs.travis-ci.com/user/languages/python/

language: python

python:
  - "3.6"

env:
  - TRAVIS_BUILD_DIR="./Notes"

install:
  - pip install -r requirements.txt

script:
  - cd $TRAVIS_BUILD_DIR
  - coverage run -m pytest

after_success:
  - coveralls

branches:
  only:
  - master
  - develop
